WITH days_in_month AS (SELECT date_part('days', date_trunc('month', CURRENT_TIMESTAMP) + interval '1 month' - date_trunc('month', CURRENT_TIMESTAMP)) AS days_in_month),
elapsed_seconds AS (SELECT date_part('epoch', timestamp - date_trunc('month', CURRENT_TIMESTAMP)) AS elapsed_seconds FROM electricity_usage_monthly WHERE month = date_part('month', CURRENT_TIMESTAMP)),
day AS (SELECT round((kwh / date_part('day', CURRENT_TIMESTAMP) * days_in_month.days_in_month)::numeric, 2) AS projected_use FROM electricity_usage_monthly, days_in_month WHERE month = date_part('month', CURRENT_TIMESTAMP)), 
hour AS (SELECT round((kwh / floor(elapsed_seconds.elapsed_seconds / 60 / 60) * days_in_month.days_in_month * 24)::numeric, 2) AS projected_use FROM electricity_usage_monthly, days_in_month, elapsed_seconds WHERE month = date_part('month', CURRENT_TIMESTAMP)), 
minute AS (SELECT round((kwh / floor(elapsed_seconds.elapsed_seconds / 60) * days_in_month.days_in_month * 24 * 60)::numeric, 2) AS projected_use FROM electricity_usage_monthly, days_in_month, elapsed_seconds WHERE month = date_part('month', CURRENT_TIMESTAMP)), 
lookback AS (SELECT CASE WHEN date_part('day', CURRENT_TIMESTAMP) > 11 THEN 0 ELSE 11 - date_part('day', CURRENT_TIMESTAMP) END AS lookback),
history AS (SELECT SUM(CASE WHEN lookback.lookback > 0 THEN kwh ELSE 0 END) AS kwh FROM lookback, electricity_sums_hourly WHERE date >= (CURRENT_TIMESTAMP::date - (lookback.lookback || ' days')::interval)::date AND date_part('month', date) = date_part('month', CURRENT_TIMESTAMP) - 1),
minuteh AS (SELECT round(((u.kwh + s.previous_year + history.kwh) / floor(elapsed_seconds.elapsed_seconds / 60 + days_in_month.days_in_month * 24 * 60 + lookback.lookback * 24 * 60) * days_in_month.days_in_month * 24 * 60)::numeric, 2) AS projected_use FROM electricity_usage_monthly u INNER JOIN electricity_statistics_monthly s ON u.month=s.month, days_in_month, elapsed_seconds, lookback, history WHERE u.month = date_part('month', CURRENT_TIMESTAMP))
INSERT INTO prediction_test (time, day, hour, minute, minuteh) VALUES (SELECT CURRENT_TIMESTAMP, day.projected_use, hour.projected_use, minute.projected_use, minuteh.projected_use FROM day, hour, minute, minuteh);
