CREATE OR REPLACE FUNCTION is_weekend(mydate DATE) RETURNS BOOLEAN AS
    'SELECT EXTRACT(''ISODOW'' FROM $1) IN (6, 7) AS is_weekend;'
LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION is_weekend(mydate TIMESTAMP) RETURNS BOOLEAN AS 
    'SELECT EXTRACT(''ISODOW'' FROM $1) IN (6, 7) AS is_weekend;' 
LANGUAGE 'sql';

CREATE OR REPLACE FUNCTION is_weekend(mydate TIMESTAMP WITH TIME ZONE) RETURNS BOOLEAN AS 
    'SELECT EXTRACT(''ISODOW'' FROM $1) IN (6, 7) AS is_weekend;' 
LANGUAGE 'sql';

